apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-robot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-robot
  template:
    metadata:
      labels:
        app: service-robot
    spec:
      containers:
      - name: service-robot
        image: robot-fleet-monitoring/service-robot-image:latest
        ports:
        - containerPort: 8001
