apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-monitor
  template:
    metadata:
      labels:
        app: service-monitor
    spec:
      containers:
      - name: service-monitor
        image: robot-fleet-monitoring/service-monitor-image:latest
        ports:
        - containerPort: 8001
