apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-restricted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-restricted
  template:
    metadata:
      labels:
        app: service-restricted
    spec:
      containers:
      - name: service-restricted
        image: robot-fleet-monitoring/service-restricted-image:latest
        ports:
        - containerPort: 8002
